version: "3"
services:
  app:    
    image: brandnewbox/bnb-ruby:2.7.2-postgresql
    command: bin/rails s
    volumes:
      - .:/app:cached
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgresql:5432
    depends_on:
      - postgresql
  postgresql:
    image: postgres:11-alpine
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
volumes:
  bundle_cache:
  my_dbdata: