version: "3"
services:
  app:    
    image: brandnewbox/bnb-ruby:2.6-postgresql
    command: bundle exec puma -C config/puma.rb
    env_file: .docker-development-vars
    volumes:
      - .:/app:cached
      - bundle_cache:/usr/local/bundle:cached
    ports:
      - "3000:3000"
  postgresql:
    image: postgres:11-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_USER=blazer
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "15432:5432"
volumes:
  bundle_cache:
  pgdata: